
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView mainTextView;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Button saveButton;
	private global::Gtk.Button restoreButton;
	private global::Gtk.Button quitButton;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Memento Editor");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.mainTextView = new global::Gtk.TextView ();
		this.mainTextView.CanFocus = true;
		this.mainTextView.Name = "mainTextView";
		this.GtkScrolledWindow.Add (this.mainTextView);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w2.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.saveButton = new global::Gtk.Button ();
		this.saveButton.CanFocus = true;
		this.saveButton.Name = "saveButton";
		this.saveButton.UseUnderline = true;
		this.saveButton.Label = global::Mono.Unix.Catalog.GetString ("Save");
		this.hbox1.Add (this.saveButton);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.saveButton]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.restoreButton = new global::Gtk.Button ();
		this.restoreButton.CanFocus = true;
		this.restoreButton.Name = "restoreButton";
		this.restoreButton.UseUnderline = true;
		this.restoreButton.Label = global::Mono.Unix.Catalog.GetString ("Restore");
		this.hbox1.Add (this.restoreButton);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.restoreButton]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.quitButton = new global::Gtk.Button ();
		this.quitButton.CanFocus = true;
		this.quitButton.Name = "quitButton";
		this.quitButton.UseUnderline = true;
		this.quitButton.Label = global::Mono.Unix.Catalog.GetString ("Quit");
		this.hbox1.Add (this.quitButton);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.quitButton]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 689;
		this.DefaultHeight = 579;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.saveButton.Clicked += new global::System.EventHandler (this.OnSaveButtonClicked);
		this.restoreButton.Clicked += new global::System.EventHandler (this.OnRestoreButtonClicked);
		this.quitButton.Clicked += new global::System.EventHandler (this.OnQuitButtonClicked);
	}
}
